/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "WebServices"

include(":SOAPServidor")
project(":SOAPServidor").projectDir = file("SOAP/Servidor")

include(":SOAPCliente")
project(":SOAPCliente").projectDir = file("SOAP/Cliente")

include(":RESTServidor")
project(":RESTServidor").projectDir = file("REST/Servidor")

include(":RESTCliente")
project(":RESTCliente").projectDir = file("REST/Cliente")