package cl.hcs.ws.soap.generado;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2025-11-20T19:22:47.207-03:00
 * Generated source version: 4.1.4
 *
 */
@WebService(targetNamespace = "http://soap.ws.hcs.cl/", name = "Servicio")
@XmlSeeAlso({ObjectFactory.class})
public interface Servicio {

    @WebMethod
    @RequestWrapper(localName = "decirHola", targetNamespace = "http://soap.ws.hcs.cl/", className = "cl.hcs.ws.soap.generado.DecirHola")
    @ResponseWrapper(localName = "decirHolaResponse", targetNamespace = "http://soap.ws.hcs.cl/", className = "cl.hcs.ws.soap.generado.DecirHolaResponse")
    @WebResult(name = "saludo", targetNamespace = "")
    public java.lang.String decirHola(

        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre
    );
}
