package cl.hcs.ws.soap.generado;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2025-11-20T19:22:47.320-03:00
 * Generated source version: 4.1.4
 *
 */
@WebServiceClient(name = "ServicioEjemplo",
                  wsdlLocation = "http://localhost:8080/soap/prueba?wsdl",
                  targetNamespace = "http://soap.ws.hcs.cl/")
public class ServicioEjemplo extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://soap.ws.hcs.cl/", "ServicioEjemplo");
    public static final QName ServicioImplPort = new QName("http://soap.ws.hcs.cl/", "ServicioImplPort");
    static {
        URL url = null;
        try {
            url = URI.create("http://localhost:8080/soap/prueba?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioEjemplo.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/soap/prueba?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioEjemplo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioEjemplo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioEjemplo() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicioEjemplo(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioEjemplo(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioEjemplo(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Servicio
     */
    @WebEndpoint(name = "ServicioImplPort")
    public Servicio getServicioImplPort() {
        return super.getPort(ServicioImplPort, Servicio.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Servicio
     */
    @WebEndpoint(name = "ServicioImplPort")
    public Servicio getServicioImplPort(WebServiceFeature... features) {
        return super.getPort(ServicioImplPort, Servicio.class, features);
    }

}
